//----- autogenerated fudge.h file


#ifndef _FUDGE_H_
#define _FUDGE_H_
#define BS               148
#define DIP_OFFSET       12
#define DPORT_OFFSET     89
#define SIP_OFFSET       80
#define SPORT_OFFSET     48
#define KSO_OFFSET       68
#define ST_OFFSET        72
#define MAGIC_OFFSET     4
#define TESTING_OFFSET   73
#define WRITE_OFFSET     138
#define SMAC_0_OFFSET    113
#define SMAC_1_OFFSET    20
#define SMAC_2_OFFSET    79
#define SMAC_3_OFFSET    56
#define SMAC_4_OFFSET    0
#define SMAC_5_OFFSET    130
#define DMAC_0_OFFSET    2
#define DMAC_1_OFFSET    42
#define DMAC_2_OFFSET    16
#define DMAC_3_OFFSET    93
#define DMAC_4_OFFSET    85
#define DMAC_5_OFFSET    46
#define INTERFACE         a98
#define DESTINATION_IP    a39
#define DESTINATION_MAC   a35
#define DESTINATION_PORT  a28
#define SOURCE_PORT       a69
#define KEYSTROKES_ONLY   a6
#define SOCKET_TRACKING   a37
#define MAGIC_VALUE       a133
#define TESTING           a62
#define WRITE_TRACKING    a145
#define FILTER_FILE       a44
#define BLOCK             a937319489
#endif
